import css from './sass/styles.scss'
import animations from './js/animations.js'
import interaction from './js/interaction.js'
import services from './js/services.js'
import contact from './js/contact.js'
import footer from './js/footer.js'
import app from './js/index.js'